# Server
TPS: 20
LogPerSecond: 50

# Environment
MapDimension: 60

# Bees
NumberBees: 150
BeeAgentVisionRange: 4.0
MaxNectar: 40 # in mg -> https://wildflowermeadows.com/2024/01/how-far-do-honeybees-fly/
BeeCreationCost: 20

# Hornets
NumberHornets: 1
HornetAgentVisionRange: 4.0

# Flowers
NumberFlowers: 30
NumberFlowerPatches: 4
MaxNectarHeld: 80 # in mg, defined as this in the code
ProducedNectarPerTurn: 3 # in mg -> https://www.miel-lerucherdelours.fr/en/content/67-the-sunflowers
