# Environment 
MapDimension: 25

# Bees
NumberBees: 10
BeeAgentVisionRange: 4.0
MaxNectar: 70 # in mg -> https://wildflowermeadows.com/2024/01/how-far-do-honeybees-fly/

# Hornets
NumberHornets: 1
HornetAgentVisionRange: 4.0

# Flowers
NumberFlowers: 15
NumberFlowerPatches: 3
